# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ThermoCheck' do
  # Comment the next line if you don't want to use dynamic frameworks
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'FBSDKLoginKit'
pod 'PKHUD'
pod 'LMGaugeViewSwift'
  use_frameworks!

  # Pods for ThermoCheck

end
